wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.13
    start_time: 1661315843
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 16
      4: 3.8.13
      5: 0.12.7
      8:
      - 2
      - 5
action_ae:
  desc: null
  value:
    _target_: models.action_ae.discretizers.k_means.KMeansDiscretizer
    action_dim: 7
    device: cuda
    num_bins: 64
    predict_offsets: true
batch_size:
  desc: null
  value: 128
betas:
  desc: null
  value:
  - 0.9
  - 0.95
data_parallel:
  desc: null
  value: false
device:
  desc: null
  value: cuda
encoder:
  desc: null
  value:
    _target_: models.resnet.resnet18
    freeze_pretrained: true
    output_dim: 512
    pretrained: true
env:
  desc: null
  value:
    action_dim: 7
    action_max:
    - 1
    - 1
    action_min:
    - -1
    - -1
    args: []
    dataset_fn:
      _target_: dataloaders.trajectory_loader.get_bridge_dataset
      data_directory: /path/to/datasets/carla_dataset
      encoder:
        _target_: models.resnet.resnet18
        freeze_pretrained: true
        output_dim: 512
        pretrained: true
      subset_fraction: 1.0
      window_size: 10
    kwargs: {}
    load_dir: /absolute/path/to/training_run/directory
    name: bridge-dummmy-v0
    obs_dim: 512
    workspace:
      _target_: workspaces.bridge_kitchen.BridgeRepWorkspace
env_vars:
  desc: null
  value:
    datasets:
      carla_multipath_town04_merge: /path/to/datasets/carla_dataset
      multimodal_push_fixed_target: /path/to/datasets/block_push_dataset
      relay_kitchen: /path/to/datasets/relay_kitchen_dataset
eval_every:
  desc: null
  value: 1
eval_prior_every:
  desc: null
  value: 1
experiment:
  desc: null
  value: bridge_data
grad_norm_clip:
  desc: null
  value: 1.0
lazy_init_models:
  desc: null
  value: true
lr:
  desc: null
  value: 0.0001
num_prior_epochs:
  desc: null
  value: 40
num_training_epochs:
  desc: null
  value: 1
num_workers:
  desc: null
  value: 32
optim:
  desc: null
  value: Adam
project:
  desc: null
  value: behavior_transformer_test
save_every:
  desc: null
  value: 1
save_latents:
  desc: null
  value: false
save_path:
  desc: null
  value: /nfs/kun2/users/asap7772/bet/exp_local/2022.08.23/213713_bridge_data
save_prior_every:
  desc: null
  value: 1
seed:
  desc: null
  value: 42
state_prior:
  desc: null
  value:
    _target_: models.latent_generators.mingpt.MinGPT
    action_dim: 7
    attn_pdrop: 0.6
    block_size: 10
    discrete_input: false
    embd_pdrop: 0.6
    focal_loss_gamma: 2.0
    input_dim: 512
    n_embd: 256
    n_head: 4
    n_layer: 3
    offset_loss_scale: 500.0
    predict_offsets: true
    resid_pdrop: 0.6
    vocab_size: ???
train_fraction:
  desc: null
  value: 0.95
weight_decay:
  desc: null
  value: 0.1
window_size:
  desc: null
  value: 10
